nelmio_api_doc:
    documentation:
        info:
            title: TODO list
            description: This is an awesome TODO list app!
            version: 1.0.0
        servers:
            - url: "http://localhost"
              description: Localhost
        components:
            securitySchemes:
                Bearer:
                    type: apiKey
                    description: 'Value: Bearer {token}'
                    name: Authorization
                    in: header
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1/(?!/doc$) # Accepts routes under /api except /api/doc
