version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.docker/nginx/conf/vhost.conf:/etc/nginx/nginx.conf
      - ./public:/var/www/html/public
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: 'postgres:14.5'
    environment:
      POSTGRES_DB: symfony_db
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
      driver: bridge
